USE sakila;

#Write SQL queries to perform the following tasks using the Sakila database:
#1. List the number of films per category.
SELECT category_id, name, COUNT(film_id)
FROM film_category
INNER JOIN category
USING (category_id)
GROUP BY category_id
ORDER BY COUNT(film_id) DESC;
#2. Retrieve the store ID, city, and country for each store
SELECT store_id, city, country
FROM store AS s
INNER JOIN address AS a 
USING (address_id)
INNER JOIN city AS cy
USING (city_id)
INNER JOIN country as co
USING (country_id);
#3. Calculate the total revenue generated by each store in dollars.
SELECT store_id, SUM(amount) AS total_revenue
FROM payment
INNER JOIN staff
USING (staff_id)
INNER JOIN store
USING (store_id)
GROUP BY store_id;
#4. Determine the average running time of films for each category.
SELECT category_id, name, AVG(length)
FROM film_category
INNER JOIN category
USING (category_id)
INNER JOIN film
USING (film_id)
GROUP BY category_id
ORDER BY AVG(length) DESC;
